declare enum GENERALMETHODS {
    CREATE = "create",
    FIND_BY_ID = "find-by-id",
    FIND_ALL = "find-all",
    FIND_ALL_PAGED = "find-all-paged",
    UPDATE = "update",
    REMOVE = "remove",
    EXISTS = "exists"
}
declare enum USERMETHODS {
    FIND_BY_CELL_PHONE = "find-by-celphone"
}
declare enum CODESMETHODS {
    VALIDATE = "validate",
    GENERATE_CODE = "generate-code"
}
export declare const USERMETHODS247: {
    FIND_BY_CELL_PHONE: USERMETHODS.FIND_BY_CELL_PHONE;
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    FIND_ALL_PAGED: GENERALMETHODS.FIND_ALL_PAGED;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export declare const USERPROFILEMETHODS247: {
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    FIND_ALL_PAGED: GENERALMETHODS.FIND_ALL_PAGED;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export declare const CODESMETHODS247: {
    VALIDATE: CODESMETHODS.VALIDATE;
    GENERATE_CODE: CODESMETHODS.GENERATE_CODE;
    FIND_BY_CELL_PHONE: USERMETHODS.FIND_BY_CELL_PHONE;
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    FIND_ALL_PAGED: GENERALMETHODS.FIND_ALL_PAGED;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export declare const GENERALMETHODS247: {
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    FIND_ALL_PAGED: GENERALMETHODS.FIND_ALL_PAGED;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export declare const VEHICLEMETHODS247: {
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    FIND_ALL_PAGED: GENERALMETHODS.FIND_ALL_PAGED;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export declare const PROFILEDOCUMENTMETHODS247: {
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    FIND_ALL_PAGED: GENERALMETHODS.FIND_ALL_PAGED;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export declare const DOCUMENTTYPEMETHODS247: {
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    FIND_ALL_PAGED: GENERALMETHODS.FIND_ALL_PAGED;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export declare const TRANSPORTMETHODS247: {
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    FIND_ALL_PAGED: GENERALMETHODS.FIND_ALL_PAGED;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
    GET_BY_USER: string;
    GET_BY_CARRIER: string;
};
export declare const TRANSPORTLOCATIONMETHODS247: {
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    FIND_ALL_PAGED: GENERALMETHODS.FIND_ALL_PAGED;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export declare const TRANSPORTQUALIFICATIONMETHODS247: {
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    FIND_ALL_PAGED: GENERALMETHODS.FIND_ALL_PAGED;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export {};
