declare enum GENERALMETHODS {
    CREATE = "create",
    FIND_BY_ID = "find-by-id",
    FIND_ALL = "find-all",
    UPDATE = "update",
    REMOVE = "remove",
    EXISTS = "exists"
}
declare enum USERMETHODS {
    FIND_BY_CELL_PHONE = "find-by-celphone"
}
declare enum CODESMETHODS {
    VALIDATE = "validate"
}
export declare const USERMETHODS247: {
    FIND_BY_CELL_PHONE: USERMETHODS.FIND_BY_CELL_PHONE;
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export declare const UserCodesMethodsVPE: {
    VALIDATE: CODESMETHODS.VALIDATE;
    FIND_BY_CELL_PHONE: USERMETHODS.FIND_BY_CELL_PHONE;
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export declare const NotificationMethodsVPE: {
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export declare const MessageMethodsVPE: {
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export declare const EmailMethodsVPE: {
    CREATE: GENERALMETHODS.CREATE;
    FIND_BY_ID: GENERALMETHODS.FIND_BY_ID;
    FIND_ALL: GENERALMETHODS.FIND_ALL;
    UPDATE: GENERALMETHODS.UPDATE;
    REMOVE: GENERALMETHODS.REMOVE;
    EXISTS: GENERALMETHODS.EXISTS;
};
export {};
