"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MICROSERVICEQUEUENAME = exports.MIDROSERVICES = void 0;
var MIDROSERVICES;
(function (MIDROSERVICES) {
    MIDROSERVICES["NOTIFICATION"] = "NOTIFICATION_SERVICE";
    MIDROSERVICES["SECURITY"] = "SECURITY_SERVICE";
})(MIDROSERVICES || (exports.MIDROSERVICES = MIDROSERVICES = {}));
var MICROSERVICEQUEUENAME;
(function (MICROSERVICEQUEUENAME) {
    MICROSERVICEQUEUENAME["NOTIFICATION"] = "notification_queue";
    MICROSERVICEQUEUENAME["SECURITY"] = "security_queue";
})(MICROSERVICEQUEUENAME || (exports.MICROSERVICEQUEUENAME = MICROSERVICEQUEUENAME = {}));
//# sourceMappingURL=microservices.enum.js.map