"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MICROSERVICEQUEUENAME = exports.MICROSERVICES = void 0;
var MICROSERVICES;
(function (MICROSERVICES) {
    MICROSERVICES["NOTIFICATION"] = "NOTIFICATION_SERVICE";
    MICROSERVICES["SECURITY"] = "SECURITY_SERVICE";
})(MICROSERVICES || (exports.MICROSERVICES = MICROSERVICES = {}));
var MICROSERVICEQUEUENAME;
(function (MICROSERVICEQUEUENAME) {
    MICROSERVICEQUEUENAME["NOTIFICATION"] = "notification_queue";
    MICROSERVICEQUEUENAME["SECURITY"] = "security_queue";
})(MICROSERVICEQUEUENAME || (exports.MICROSERVICEQUEUENAME = MICROSERVICEQUEUENAME = {}));
//# sourceMappingURL=microservices.enum.js.map